export const INIT_PIC_LIST = 'INIT_PIC_LIST'
export const SET_PIC_LIST = 'SET_PIC_LIST'
export const CATE_LIST = 'CATE_LIST'
export const ADD_TO_MESSAGES = 'ADD_TO_MESSAGES'
export const CLEAN_MESSAGES = 'CLEAN_MESSAGES'